apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-log-pvc
spec:
  storageClassName: localmac
  volumeName: local-log-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
